# Generated by Django 4.0 on 2022-01-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGrupo5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='tipoInstrumento',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipoinstrumento',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
